services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/bookstore.sql:/docker-entrypoint-initdb.d/bookstore.sql
    ports:
      - "3306:3306"
    networks:
      - db_net

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    networks:
      - db_net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - db_net

  api:
    build:
      context: .
      dockerfile: ./SimpleCSApplication/Dockerfile
    container_name: simplecsapp
    ports:
      - "8080:8080"
    networks:
      - db_net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    depends_on:
      - mysql
      - mongo
      - redis

networks:
  db_net:
    driver: bridge
