FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["SimpleCSApplication/SimpleCSApplication.csproj", "SimpleCSApplication/"]
RUN dotnet restore "SimpleCSApplication/SimpleCSApplication.csproj"
COPY . .
WORKDIR "/src/SimpleCSApplication"
RUN dotnet build "SimpleCSApplication.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SimpleCSApplication.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "SimpleCSApplication.dll"]